### ISSUE TITLE
error at  model.learn() when goseek-ppo.ipynb is executed

### ISSUE THREAD

**Issue by thezest76** [MIT-TESSE/goseek-challenge#11]
Hello,
Thanks for the nice SW
Could you please help me with the error message below ? 
I tried to eliminate the callback function in model.learn(), but then robot stuck at somewhere, and do nothing...
It isn't an easy fix for me because I am not good at python.

Best

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-a8bc6236ba26> in <module>
----> 1 model.learn(total_timesteps=total_timesteps, callback=save_checkpoint_callback)

~/anaconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py in learn(self, total_timesteps, callback, log_interval, tb_log_name, reset_num_timesteps)
    334                 callback.on_rollout_start()
    335                 # true_reward is the reward without discount
--> 336                 rollout = self.runner.run(callback)
    337                 # Unpack
    338                 obs, returns, masks, actions, values, neglogpacs, states, ep_infos, true_reward = rollout

~/anaconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/common/runners.py in run(self, callback)
     46         self.callback = callback
     47         self.continue_training = True
---> 48         return self._run()
     49 
     50     @abstractmethod

~/anaconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py in _run(self)
    486             if self.callback is not None:
    487                 # Abort training early
--> 488                 if self.callback.on_step() is False:
    489                     self.continue_training = False
    490                     # Return dummy values

~/anaconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/common/callbacks.py in on_step(self)
     87         self.num_timesteps = self.model.num_timesteps
     88 
---> 89         return self._on_step()
     90 
     91     def on_training_end(self) -> None:

~/anaconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/common/callbacks.py in _on_step(self)
    216     def _on_step(self) -> bool:
    217         if self.callback is not None:
--> 218             return self.callback(self.locals, self.globals)
    219         return True
    220 

<ipython-input-10-a9e34596ddff> in save_checkpoint_callback(local_vars, global_vars)
      3 
      4 def save_checkpoint_callback(local_vars, global_vars):
----> 5     total_updates = local_vars["update"]
      6     if total_updates % 1000 == 0:
      7         local_vars["self"].save(str(log_dir / f"{total_updates:06d}.pkl"))

KeyError: 'update'

**Comment by ZacRavichandran** [comment]
Hi,

Glad that you like it! 

In response to the two issues you observed: 

1.  KeyError: 'update'

Did you edit the notebook at all before getting this error? 

2. Eliminating the callback function

How did you eliminate the callback function? Was it like the following:

```python
model.learn(total_timesteps=total_timesteps)  # don't pass in `callback=save_checkpoint_callback`
```

(Note that this will not save intermediate checkpoints, so you will have to add the following to save the model after  training)

```python
model.save("goseek_ppo_model")
```

**Comment by thezest76** [comment]
Hi,

Thanks for the quick reply.

_Did you edit the notebook at all before getting this error?_

I made one modification.
filename = Path("../../goseek-challenge/simulator/goseek-v0.1.0.x86_64")
to
filename = Path("../../goseek-challenge/simulator/goseek-v0.1.3.x86_64")

_How did you eliminate the callback function? Was it like the following:_

Yes, I did **model.learn(total_timesteps=total_timesteps)**
Where should I put _model.save("goseek_ppo_model")_ ? If this line stays after _model.learn()_, it won't fix my problem because my problem is at the learning stage.
GOSEEK screen doesn't show any progress. That is, the agent is not moving, but stuck at the same position.

Thanks for your help

**Comment by ZacRavichandran** [comment]
We just pushed a round of updates to [`tesse-gym`](https://github.com/MIT-TESSE/tesse-gym) that may address your issues, could you try recloning? 

If that doesn't work, where in the code does it hang? If you interrupt the notebook when the agent is stuck and share the stacktrace, we should be able to find where the process is held up.

**Comment by thezest76** [comment]
Hello,

Thanks for your help.

I recloned the updated _tesse-gym_ based on your advice.
The callback function still produces the same error.

However, it seems that the training works if I disable the callback function. The agent moves around during the training. _goseek_ppo_model.zip_ is generated when the training is finished. 

I made one modification, though.
"../../goseek-challenge/simulator/goseek-v0.1.4.x86_64"
to 
"../../goseek-challenge/simulator/goseek-v0.1.3.x86_64"
Do you know if this modification is related to the callback function issue?

Best

**Comment by ZacRavichandran** [comment]
Glad the reclone worked (at least for the first issue)! 

About the callback function - I don't think that modification is related. It sounds more like an issue with stable-baselines logging. To debug, could you add the following line in the callback function.

```python
def save_checkpoint_callback(local_vars, global_vars):
    print(f"=== local vars ===\n{local_vars.keys()}")  # add this line 
    total_updates = local_vars["update"]
    if total_updates % 1000 == 0:
        local_vars["self"].save(str(log_dir / f"{total_updates:06d}.pkl"))
```

Hopefully, this will give us a little more insight into the issue.

**Comment by thezest76** [comment]
Thanks for your prompt reply.
What I get is as below

_=== local vars ===
dict_keys(['self', 'total_timesteps', 'callback', 'log_interval', 'tb_log_name', 'reset_num_timesteps', 'cliprange_vf', 'new_tb_log', 'writer', 't_first_start', 'n_updates'])_

Then, I tried to change set _local_vars["update"]_ to _local_vars["n_updates"]_. 
The subsequent program runs w/o any error message. However, _local_vars["n_updates"]_ is always 390; This value doesn't increment itself but stays the same. As a results, _total_updates % 1000 == 0_ is always false. 
Is there anything I am missing here ?

Best

**Comment by ZacRavichandran** [comment]
My apologies for such a delayed response. 

What version of stable baselines are you using? Perhaps there was an update in logging. Also, looking at the available keys, `total_timestamps` may give progress updates.

**Comment by itroff** [comment]
You can use CheckpointCallback for periodically saving model weights:
`from stable_baselines.common.callbacks import CheckpointCallback
checkpoint_callback = CheckpointCallback(save_freq=2000, save_path='./results/',
                                         name_prefix='ppo2-checkpoint')
model.learn(total_timesteps=total_timesteps,  callback=checkpoint_callback)`

**Comment by thezest76** [comment]
This saves models at checkpoints. Thanks for your help.
But, I am still not sure why the original code doesn't work. 
May be some SW version issue...

**Comment by ZacRavichandran** [comment]
Glad it's working now. The original issue is strange. Like you said, perhaps it's a version issue? I'm on stable-baselines `v2.9.0`

**Comment by itroff** [comment]
```
pip show stable-baselines
Name: stable-baselines
Version: 2.10.0
```
In this version in local_vars don`t exist key 'update'

**Comment by ZacRavichandran** [comment]
Ok, good to know. Using `CheckpointCallback` is a better solution anyway, I'll update the example notebook. Thanks @itroff!
