### ISSUE TITLE
decoding observations: IndexError: too many indices for array

### ISSUE THREAD

**Issue by pushkalkatara** [MIT-TESSE/goseek-challenge#13]
```
    rgb, segmentation, depth, self.agent_pose = decode_observations(obs)
  File "/home/pushkalkatara/miniconda3/envs/goseek/lib/python3.7/site-packages/tesse_gym-0.1.5-py3.7.egg/tesse_gym/tasks/goseek/goseek_full_perception.py", line 119, in decode_observations
IndexError: too many indices for array
```

while printing obs numpy array
```
[0.80392157 0.81960784 0.80392157 ... 0.         0.         0.        ]
```

I think the index error is due to zeros in the npy array. what might be the reason for 0s.

**Comment by ZacRavichandran** [comment]
The last three elements of the observation correspond to the agent's pose, so a sequence of 0s is not necessarily an issue. 

`decode_observations` expects as input a shape `(N, O)` array where `N` is the number of environments (>=1) and `O` is the observation shape (default 384003). It looks like the obs array is shape `(O, )`, which would be causing the `IndexError`

We can add some handling for that case. In the meantime, could you see is passing in `obs[np.newaxis]` solves the problem? Thanks!
