### ISSUE TITLE
Why our 'Execution Time' is None?

### ISSUE THREAD

**Issue by Dongbox** [MIT-TESSE/goseek-challenge#18]
![Screenshot from 2020-05-08 21-29-11](https://user-images.githubusercontent.com/36894425/81411772-6cc0d780-9175-11ea-9373-15bba4033496.png)

**Comment by griffith826** [comment]
Hi, looks like it worked! That field isn't getting populated correctly somewhere on our end -- web interfacing, not any of the challenge code. This shouldn't affect any results, but we will take a look and see if we can square it away.
