### ISSUE TITLE
Is it possible to decrease simulator resolution?

### ISSUE THREAD

**Issue by lexavtanke** [MIT-TESSE/goseek-challenge#20]
Hello,

Is it possible to decrease simulator resolution from 320*240 to may be 160*120? How it could be done?

And may be there is a way to force the Unity to decrease fps? It seem overhead to render 500 fps if in real agent use only 30 fps.

**Comment by ZacRavichandran** [comment]
Hi,

You can adjust resolution, although for submissions this will be fixed at (H, W) = (240, 320)

If you'd like to adjust resolution through the gym environment, you could wrap the method [set_all_camera_params](https://github.com/MIT-TESSE/tesse-gym/blob/master/src/tesse_gym/core/utils.py#L76). This will update the camera resolution upon initialization. You'll also have to update the expected observation shape.

This would look like: 

```python
from tesse_gym.core.utils import set_all_camera_params
from tesse_gym.tasks.goseek import GoSeekFullPerception

# update expected observation shape
class GoSeekUpdatedResolution(GoSeekFullPerception):
   shape = (120, 160, 5)

# update simulator cameras on init
def set_resolution(tesse_gym):
   set_all_camera_params(tesse_gym, height_in_pixels=160, width_in_pixels=160)

env = GoSeekUpdatedResolution(...,  # rest of args
   init_hook=set_resolution 
)
```

As for the unity fps, there isn't an exposed method for doing that. However, the `step_rate` parameter (if that's where the 30 fps is coming from) controls [step mode](https://github.com/MIT-TESSE/tesse-core#timing-modes), not physical fps. Step mode keeps game time constant, but physical time (meaning how fast the agent receives updates) will be faster.
