### ISSUE TITLE
Error in testing eval.py 

### ISSUE THREAD

**Issue by vidhiJain** [MIT-TESSE/goseek-challenge#21]
As per the installation instructions, I am trying to test the install with the eval.py script but failing to do so. Here is the trace of the command `python eval.py --agent-config baselines/config/random-agent.yaml --episode-config config/check-ground-truth.yaml`. 
```
Set current directory to /home/vidhi/goseek-challenge
Found path: /home/vidhi/goseek-challenge/simulator/goseek-v0.1.4.x86_64
Mono path[0] = '/home/vidhi/goseek-challenge/simulator/goseek-v0.1.4_Data/Managed'
Mono config path = '/home/vidhi/goseek-challenge/simulator/goseek-v0.1.4_Data/MonoBleedingEdge/etc'
Preloaded 'ScreenSelector.so'
Logging to /home/vidhi/.config/unity3d/Editor/Player.log
Traceback (most recent call last):
  File "eval.py", line 85, in <module>
    results = main(episode_cfg, agent_args)
  File "eval.py", line 63, in main
    ground_truth_mode=episode_args.ENV.ground_truth_mode,
  File "/home/vidhi/tesse-gym/src/tesse_gym/tasks/goseek/goseek_benchmark.py", line 70, in __init__
    ground_truth_mode=ground_truth_mode,
  File "/home/vidhi/tesse-gym/src/tesse_gym/tasks/goseek/goseek.py", line 99, in __init__
    ground_truth_mode=ground_truth_mode,
  File "/home/vidhi/tesse-gym/src/tesse_gym/core/tesse_gym.py", line 120, in __init__
    self.env.request(SceneRequest(scene_id))
  File "/home/vidhi/anaconda3/envs/goseek/lib/python3.7/site-packages/tesse-0.1.2-py3.7.egg/tesse/env.py", line 79, in request
OSError: [Errno 98] Address already in use
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/vidhi/tesse-gym/src/tesse_gym/core/tesse_gym.py", line 267, in close
    if not self.ground_truth_mode:
AttributeError: 'GoSeekFullPerception' object has no attribute 'ground_truth_mode'
```

**Comment by ZacRavichandran** [comment]
Based on this error: `OSError: [Errno 98] Address already in use`, it seems that the required port,  9000, could not be connected to. 

Could you check if anything is blocking that port by running:

```sudo lsof -i | grep 9000 ```

**Comment by vidhiJain** [comment]
Yes, indeed. I realize that I cannot stop the previously running docker on that port. Is there a way to change the required port for goseek?

**Comment by ZacRavichandran** [comment]
Yes, that's defined in the the configuration file. You will need to increment the [default port values](https://github.com/MIT-TESSE/tesse-gym/blob/master/src/tesse_gym/tasks/goseek/goseek_config.py) by 1. Thus, `check-ground-truth` would look like the following: 


```yaml
ENV:
   sim_path: 'simulator/goseek-v0.1.4.x86_64'
   position_port: 9001
   metadata_port: 9002
   image_port:  9003
   step_port: 9006

EPISODE:
   scenes: [3, 5]
   n_targets: [30, 30]
   episode_length: [400, 400]
   random_seeds: [10, 100]
```

Also, if you use the [baseline example](https://github.com/MIT-TESSE/tesse-gym/blob/master/baselines/goseek-ppo.ipynb), you can increment the default port values by changing the line `network_config=get_network_config(worker_id=rank)` to `network_config=get_network_config(worker_id=rank+1)`

**Comment by vidhiJain** [comment]
Thanks!
