### ISSUE TITLE
docker install kimera failure 

### ISSUE THREAD

**Issue by JD-ETH** [MIT-TESSE/goseek-challenge#25]
I receive this error when trying to install the kimera docker: 
```
Fetched 545 MB in 1min 27s (6,232 kB/s)
E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/p/python-catkin-pkg-modules/python-catkin-pkg-modules_0.4.20-1_all.deb  404  Not Found [IP: 64.50.236.52 80]
E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/p/python-catkin-pkg/python-catkin-pkg_0.4.20-100_all.deb  404  Not Found [IP: 64.50.236.52 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
``` 

Did anyone suceeded in installing kimera locally?

**Comment by ZacRavichandran** [comment]
I'll haven't seen the `404 Not Found` error before and will have to look into that. The closest I've seen is a ` 403  NetworkCongestion` error which seems to be related to network/VPN issues. For that, rebuilding does the trick. 

 As for installing kimera locally, you should be able to do so by running the commands in the dockerfile. However, this will take a bit of time to setup as compared to using docker.

**Comment by JD-ETH** [comment]
rebuilding has the same issue. It looks rather time consuming trying to install it locally with all the steps. I will try and wait if you can find the reason first. Thanks!

**Comment by JD-ETH** [comment]
@ZacRavichandran Have you found time for that?

**Comment by ZacRavichandran** [comment]
@JD-ETH I still haven't been able to reproduce the issue on my end. However, it looks like there was a recent [update](https://answers.ros.org/question/352605/different-versions-of-python3-catkin-pkg-modules-are-distributed-on-packagesrosorg/) to the ROS mirrors that may fix the problem. Based on that, could you try to build with `--no-cache`?

**Comment by JD-ETH** [comment]
You are right, I was caught in the unfortunate moment. Thanks!
