### ISSUE TITLE
Simulator high CPU usage

### ISSUE THREAD

**Issue by itroff** [MIT-TESSE/goseek-challenge#28]
Hello,
why is simulator take o lot of CPU time? It is about 4-core per one simulator instance. 
Is there a way to reduce cpu usage on system?
Configuration is  Ubuntu 18.04, AMD Ryzen 3600, RTX2060

![Screenshot from 2020-05-20 11-55-27](https://user-images.githubusercontent.com/11217861/82426988-30ed1280-9a91-11ea-8c71-40bfd0058233.png)

**Comment by ZacRavichandran** [comment]
Hello,
There isn't a way to configure cpu usage. But looking at the diagnostic output, could there be extra running processes that need to be stopped? You could try to remove all running instances with the command `killall goseek-v0.1.4.x86_64`

**Comment by itroff** [comment]
Thank you for reply! Unfortunately, kill processes didn`t help me.
But I found, that recompilling some parts of  tesse-core project solved my problem.
1. Download Unity 2019 and tesse-example-project
2. Adding folowing line in https://github.com/MIT-TESSE/tesse-core/blob/master/scripts/tesse_base.cs in Start() method for disabling VSync:
```
Application.targetFrameRate = cla_parser.capture_rate;
QualitySettings.vSyncCount = 0;
Time.captureFramerate = cla_parser.capture_rate;
```
3. Compiling Unity project tesse-core.
4. Replace file  ./goseek-challenge/simulator/goseek-v0.1.4_Data/Managed/Assembly-CSharp.dll from fresh Unity tesse-core building
5. In https://github.com/MIT-TESSE/tesse-gym/blob/master/src/tesse_gym/core/tesse_gym.py in _init_ function add --capture_rate parameter
```
 self.proc = subprocess.Popen(
                [
                    sim_path,
                    "--listen_port",
                    str(int(network_config.position_port)),
                    "--send_port",
                    str(int(network_config.position_port)),
                    "--set_resolution",
                    str(self.shape[1]),
                    str(self.shape[0]),
                    "--capture_rate",
                    "60"
                ]
)
```
After this I could running more than 6 simulator`s instance on my machine.
CPU consuming amounted ~150%  per one simulator instance.
