### ISSUE TITLE
Instructions for submission?

### ISSUE THREAD

**Issue by MasterScrat** [MIT-TESSE/goseek-challenge#3]
Hello,

I don't understand how online submission works.

The README specifies that:

> Instructions for submitting agents online will be available according to the competition timeline above.

Has this been published anywhere yet?

I also can't seem to find the goseek-challenge on the EvalAI challenge list (https://evalai.cloudcv.org/web/challenges/list)

**Comment by griffith826** [comment]
Hi,

We will be posting instructions in the next day or two. Sorry for the confusion -- we sent out an email to those who signed up for emails at https://mit-spark.github.io/PAL-ICRA2020/#/features/04-GOSEEK-Challenge. I'll post the updated timeline now to the github page.

In light of the changes to ICRA, we decided to delay opening of submissions until mid-April and will close the competition on May 20th.

**Comment by MasterScrat** [comment]
Great thanks :D
