### ISSUE TITLE
Robot falls down

### ISSUE THREAD

**Issue by han-kyung-min** [MIT-TESSE/goseek-challenge#33]
Hello,

Thanks for the excellent simulator.

I was hoping to get a piece of advice for the problem I am having with training my agent using the Tesse environment. 

In some cases, the robot physically falls under the floor in the middle of training.
It appears to me that this event occurs when my script calls reset() function to reset the pose of the robot.
The robot initialized inside of the office most of the cases. However, in some cases, the robot locates itself outside of the building, causing it to fall down. I enabled "restart on collision event", so there is no chance that the the robot passes through walls.

I thought about using the "z" position to reset the robot again if "z" goes below a certain threshold. However, "z" doesn't represent the actual height of the robot when it starts falling.   

Could you please tell me how to solve this problem?

Best,

**Comment by ZacRavichandran** [comment]
Hi,

I'm glad that you like it!

This issue will be patched in the next round of scene releases (see [this comment](https://github.com/MIT-TESSE/goseek-challenge/issues/32#issuecomment-685754622)).  

In the meantime, Unity uses a [left-handed coordinate system](https://github.com/MIT-TESSE/tesse-core#coordinate-system) so the "y" position will indicate a fall. The threshold method you described should work using that coordinate, which can be retrieved via [`_get_agent_position`](https://github.com/MIT-TESSE/tesse-gym/blob/master/src/tesse_gym/core/tesse_gym.py#L442). 

Hope this helps!

**Comment by han-kyung-min** [comment]
Sorry for the late reply.

I tried the threshold method, and the method seems working. I had to add a dummy rotation step() right after the reset() though. Thanks for your help. Hoping to see the new scenes soon.

Best,
