### ISSUE TITLE
How to record rosbag?

### ISSUE THREAD

**Issue by p-akanksha** [MIT-TESSE/goseek-challenge#34]
Hi, 

I want to record a rosbag of the simulation to use as input for Kimera_Semantic. However, when I use rostopic list, I don't see any topic being published by the simulator. Can someone help me with that? 

Thanks,
Akanksha

**Comment by ZacRavichandran** [comment]
Hi,

To decrease required computation, ground truth semantic segmentation isn't published by default. To enable, you case set `publish_segmentation` to true in [`run_goseek_perception.launch`](https://github.com/MIT-TESSE/tesse-gym-bridge/blob/master/launch/run_goseek_perception.launch#L21):

`roslaunch tesse_gym_bridge run_goseek_perception.launch publish_segmentation:=true`

If you're using `test_locally.py`, you can set the above argument [here](https://github.com/MIT-TESSE/goseek-challenge/blob/master/test_locally.py#L89). 

Hope this helps!

**Comment by p-akanksha** [comment]
Thanks Zac! I was using the executable file (goseek-v0.1.4.x86_64) and trying to collect the rosbag. That did not work for me. But I was able to collect the bag using [tesse_gym_bridge](https://github.com/MIT-TESSE/tesse-gym-bridge).

Thanks for the help!
