### ISSUE TITLE
Simulator Stop(version 0.1.3)

### ISSUE THREAD

**Issue by ZHMA1996** [MIT-TESSE/goseek-challenge#7]
Is is possible that the simulator would suddenly stop ?

when testing the simulator with an agent taking random action, the simulator just go forward several 

steps and just stop. And no similar phenomenon was observed in version 0.1.0.

**Comment by ZHMA1996** [comment]
Especially when the agent take the action 3

**Comment by ZHMA1996** [comment]
It seems the program stops in the function advance_game_time, could anyone explain in detail and how to solve it.

**Comment by ZacRavichandran** [comment]
Hi,

Did this happen when running:

```sh
python eval.py --agent-config baselines/config/random-agent.yaml --episode-config config/check-ground-truth.yaml
```

or are there other cases where you've observed that behavior?

**Comment by ZHMA1996** [comment]
Hi

when running the command you provided, this behavior didn't happen.

**Comment by ZacRavichandran** [comment]
Good to know. Is there a command we can use to replicate the issue?

**Comment by ZHMA1996** [comment]
When testing my own agent, the behavior happened. I tried to figure out why and use a for loop to 

iterate over every step and found that the simulator would stop when fetching fruits. In this setting, I 

created a Vector Env using the library, stable-baselines.  After I commented out the function 

advance_game_time in the source code and then the simulator could work again.

**Comment by ZacRavichandran** [comment]
Thanks for the description. If you're still having issues, could you try setting the `step_rate` argument in `GoseekFullPerception` to 20 (doesn't have to be 20 specifically, but in that range would be good). 

In the [baseline notebook](https://github.com/MIT-TESSE/tesse-gym/blob/master/baselines/goseek-ppo.ipynb), this would look like:

```python
env = GoSeekFullPerception(
                str(filename),
                step_rate=20,
                network_config=get_network_config(worker_id=rank),
                n_targets=n_targets,
                episode_length=episode_length,
                scene_id=scene_id[rank],
                target_found_reward=target_found_reward,
            )
```

**Comment by ZHMA1996** [comment]
Thanks for your reply. This problem could be solved after setting the `step_rate` argument !

**Comment by ZacRavichandran** [comment]
Good to know! I'll update the baseline notebook to suggest that!

**Comment by pushkalkatara** [comment]
Faced same issue in v0.1.4. Adding step_rate=20 solved the issue.
