### ISSUE TITLE
Shape of the observation

### ISSUE THREAD

**Issue by achuwilson** [MIT-TESSE/goseek-challenge#8]
Hi, I was trying as instructed here : https://github.com/MIT-TESSE/goseek-challenge/blob/master/Instructions.md. But the observation.shape is of shape (3932163,) instead of (384003,) , as in the documentation. 

Hence the function decode_observations throws an index error as follows

File "/home/acw/works/goseek/tesse-gym/src/tesse_gym/tasks/goseek/goseek_full_perception.py", line 124, in decode_observations
    imgs = observation[:, :-3].reshape(img_shape)
IndexError: too many indices for array

**Comment by achuwilson** [comment]
Similar error shows up with the ppo training example too.
when calling model.learn(total_timesteps=total_timesteps, callback=save_checkpoint_callback)

it stops with the following error after a while
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-a8bc6236ba26> in <module>
----> 1 model.learn(total_timesteps=total_timesteps, callback=save_checkpoint_callback)

~/miniconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py in learn(self, total_timesteps, callback, log_interval, tb_log_name, reset_num_timesteps)
    334                 callback.on_rollout_start()
    335                 # true_reward is the reward without discount
--> 336                 rollout = self.runner.run(callback)
    337                 # Unpack
    338                 obs, returns, masks, actions, values, neglogpacs, states, ep_infos, true_reward = rollout

~/miniconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/common/base_class.py in runner(self)
    792     def runner(self) -> AbstractEnvRunner:
    793         if self._runner is None:
--> 794             self._runner = self._make_runner()
    795         return self._runner
    796 

~/miniconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py in _make_runner(self)
     98     def _make_runner(self):
     99         return Runner(env=self.env, model=self, n_steps=self.n_steps,
--> 100                       gamma=self.gamma, lam=self.lam)
    101 
    102     def _get_pretrain_placeholders(self):

~/miniconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py in __init__(self, env, model, n_steps, gamma, lam)
    447         :param lam: (float) Factor for trade-off of bias vs variance for Generalized Advantage Estimator
    448         """
--> 449         super().__init__(env=env, model=model, n_steps=n_steps)
    450         self.lam = lam
    451         self.gamma = gamma

~/miniconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/common/runners.py in __init__(self, env, model, n_steps)
     29         self.batch_ob_shape = (n_envs * n_steps,) + env.observation_space.shape
     30         self.obs = np.zeros((n_envs,) + env.observation_space.shape, dtype=env.observation_space.dtype.name)
---> 31         self.obs[:] = env.reset()
     32         self.n_steps = n_steps
     33         self.states = model.initial_state

ValueError: could not broadcast input array from shape (2,3932163) into shape (2,384003)

``

**Comment by ZacRavichandran** [comment]
Hi,

It looks like camera resolution isn't being set correctly. After starting the simulator through the ppo notebook, could you run the following to check the camera parameters:

```python 
from tesse.msgs import *; from tesse.env import Env;
print(Env().request(CameraInformationRequest()).metadata)
```

The resolution of `rgb_left`, `segmentation`, and `depth`, the cameras used to create the observation, should be `240x320` like so:

```python
<TESSE_Agent_CameraInfo_v0.5>
  <camera_info>
    <name>rgb_left</name>
    <id>0</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='-0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>rgb_right</name>
    <id>1</id>
    <parameters height='768' width='1024' fov='60'/>
    <position x='0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>segmentation</name>
    <id>2</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='-0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>depth</name>
    <id>3</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='-0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>3pv</name>
    <id>4</id>
    <parameters height='768' width='1024' fov='90'/>
    <position x='0' y='0.7' z='-1.2'/>
    <rotation x='0.1100685' y='0' z='0' w='0.993924'/>
    <draw_distance near='0.3' far='150'/>
  </camera_info>
  <camera_info>
    <name>instance_segmentation</name>
    <id>5</id>
    <parameters height='768' width='1024' fov='60'/>
    <position x='0.05000019' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
</TESSE_Agent_CameraInfo_v0.5>
```

The error you're getting indicates that the cameras are still on the default resolution of `768 x 1024`. RGB, segmentation, and depth have a total of 5 channels. Those, with 3 values for pose, gives  `5 x 768 x 1024 + 3 = 3932163` instead of the expected `5 x 240 x 320 + 3 = 384003`.

**Comment by achuwilson** [comment]
Hi, Thanks for the quick reply.
It looks like that the issue is fixed somehow now. The output I get with the above command is 
`<TESSE_Agent_CameraInfo_v0.5>
  <camera_info>
    <name>rgb_left</name>
    <id>0</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='-0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>rgb_right</name>
    <id>1</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>segmentation</name>
    <id>2</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='-0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>depth</name>
    <id>3</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='-0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>3pv</name>
    <id>4</id>
    <parameters height='240' width='320' fov='90'/>
    <position x='0' y='0.7' z='-1.2'/>
    <rotation x='0.1100685' y='0' z='0' w='0.993924'/>
    <draw_distance near='0.3' far='150'/>
  </camera_info>
  <camera_info>
    <name>instance_segmentation</name>
    <id>5</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='0.05000019' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
</TESSE_Agent_CameraInfo_v0.5>
`

**Comment by ZacRavichandran** [comment]
Good to hear, the above values look correct. Let us know if you run into any related issues.
